### PR TITLE
Migrate to AirseekerRegistry contract

### LINKED ISSUE #163: Upgrade to the new AirseekerRegistry contract
The `DapiDataRegistry` contract is going to be slightly changed and renamed to `AirseekerRegistry`.

It should support the extended multicall functionality in order to get the chain timestamp, block and ID in order to verify the chain information.

Blocked until the mentioned contract changes are implemented.

### PR DESCRIPTION
**Pull request by Siegrift**
Closes https://github.com/api3dao/airseeker-v2/issues/163

## Rationale

The contract is a bit more generic and allows supporting data feeds via ID (not dAPI name). The code was previously tailored to dAPIs and used often used `dapi` for naming. These are renamed to a more generic and accurate `dataFeed` instead.

The contract name changed from `DapiDataRegistry` to `AirseekerRegistry`. It uses `Api3ServerV1` to read the data feed details and can return no data in case the data feed is not registered. This is now explicitly handled by skipping such data feeds and logging a warning.

Both spec and diagrams are updated accordingly.

### CODE REVIEW

**Review by Siegrift — COMMENTED** [review]
@peterjurco you can take a look at https://github.com/api3dao/airseeker-v2/blob/upgrade-contracts3/test/setup/contract.ts to see how contracts are setup and https://github.com/api3dao/airseeker-v2/blob/upgrade-contracts3/src/update-feeds-loops/contracts.ts how to work with it.

**Comment by bbenligiray** [comment]
I made some changes to AirseekerRegistry that I haven't decided to keep yet. Giving a heads up because they probably cause the CI of this branch to fail.

**Review by aquarat — APPROVED** [review]
This is of course a pretty big PR, but I don't see anything incorrect/inefficient/etc.

So LGTM 💪

**Comment by Siegrift** [comment]
Thanks everyone 💪 .

**Pull request merged**
